### ISSUE TITLE
Arbitrary fonts

### ISSUE THREAD

**Issue by ACBob** [ACBob/VoxelThingYeah#25]
Specify character ranges and specific characters that render with X texture. Internally stitch it into one.

```toml

[fonts] # Note that named ones (such as ascii, cp437, etc.) are hard-coded to 16x16 tiles.
ascii="" # Give a path to make a texture treated as ASCII (0-127)
cp437="font.png" # Maps characters to use the right positions as if we use CP437. 0,0 is NUL, 1,0 is Smiley, etc.
jap="" # Japanese or whatever
manual="blah.png" # Specify custom positions on the texture file for characters.

[blah.png]
'a' = [0,0]
'0x2593' = [1,0]

```

Why would we want it?\
Different, arbitrary language support.

![image](https://user-images.githubusercontent.com/46695136/135093442-f68f2c16-2be9-4646-808d-09ced97b9eb3.png)
_Public Domain, https://commons.wikimedia.org/w/index.php?curid=10573855_
