### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by ACBob** [ACBob/VoxelThingYeah#28]
Translation into arbitrary languages.

*How* it is done, is up in the air. [GNU GetText](https://en.wikipedia.org/wiki/Gettext) looks interesting, but doesn't seem like it'd merge well with the TOML I want at all. It may be worth committing the [sin](https://stackoverflow.com/questions/1236256/how-do-you-decide-whether-to-use-a-library-or-write-your-own-implementation) of _rolling our own translation library._ ⛈️

`languages.toml` & language files?\
e.g
```toml
[en_gb]
friendly_name = "English (British)"
lang_file = "lang/en-gb.toml"

[en_us]
friendly_name = "English (Simplified)"
lang_file = "lang/en-us.toml"

[da]
friendly_name = "Dansk"
lang_file = "lang/da.toml"
```

and then `en_gb.toml`
```toml
[gui]
done = "Done"
confirm = "OK"
cancel = "Cancel"
exit = "Back"
```

and posterity, `da.toml`
```toml
[gui]
done = "Gjort"
confirm = "Bekræfte"
cancel = "Aflyse"
exit = "Udgang"
```

There should be no limit! I want custom languages to be supported. adding something like
```toml
[yarr]
friendly_name = "The Seven Seas"
lang_file = "yarr.toml"
```
To be possible in someone's resource pack for a pirate themed game.
